version: '3.9'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'dentist'
volumes:
  postgres: