version: '3.9'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      - DB_USER=root
      - DB_PASSWORD=1234
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  mysqldb: