version: '3.9'
services:
  mysqldb:
    image: mysql:8
    env_file: ./.env
    container_name: mysql-docker
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_UPASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'